"""Email the brief via Resend, as styled HTML. No-op if RESEND_API_KEY is unset.

Credentials: RESEND_API_KEY + EMAIL_TO. The Markdown brief is rendered to HTML so it
reads cleanly in an inbox; the raw Markdown is included as a plain-text fallback.
"""
from __future__ import annotations

import httpx

import config

_STYLE = """
  body { margin:0; background:#f6f7f9; }
  .wrap { max-width:640px; margin:0 auto; padding:24px 20px;
          font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
          color:#1f2937; line-height:1.55; }
  h1 { font-size:20px; margin:0 0 16px; color:#111827; }
  h2 { font-size:13px; text-transform:uppercase; letter-spacing:.05em;
       margin:28px 0 10px; color:#6b7280; }
  h3 { font-size:17px; margin:22px 0 8px; color:#4f46e5; }
  p { margin:7px 0; }
  a { color:#2563eb; text-decoration:none; }
  ul { margin:8px 0; padding-left:20px; }
  li { margin:5px 0; }
  hr { border:0; border-top:1px solid #e5e7eb; margin:20px 0; }
  .footer { color:#9ca3af; font-size:12px; margin-top:28px; }
"""


def _to_html(subject: str, body: str) -> str:
    try:
        import markdown

        inner = markdown.markdown(body, extensions=["extra", "sane_lists", "nl2br"])
    except Exception:  # markdown not installed — degrade to readable plain text
        import html as _html

        inner = f"<pre style='white-space:pre-wrap'>{_html.escape(body)}</pre>"

    return (
        f"<!doctype html><html><head><meta charset='utf-8'>"
        f"<style>{_STYLE}</style></head><body><div class='wrap'>"
        f"<h1>{subject}</h1>{inner}"
        f"<p class='footer'>Generated by Problembrief.</p>"
        f"</div></body></html>"
    )


def send_email(subject: str, body: str) -> bool:
    if not config.RESEND_API_KEY:
        print("  - email: skipped (set RESEND_API_KEY — see README 'Email setup')")
        return False
    if not config.EMAIL_TO:
        print("  ! email: RESEND_API_KEY is set but EMAIL_TO is empty")
        return False
    try:
        r = httpx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {config.RESEND_API_KEY}"},
            json={
                "from": config.EMAIL_FROM,
                "to": [config.EMAIL_TO],
                "subject": subject,
                "html": _to_html(subject, body),
                "text": body,  # plain-text fallback
            },
            timeout=20,
        )
        r.raise_for_status()
        print(f"  - email: sent to {config.EMAIL_TO}")
        return True
    except Exception as e:
        print(f"  ! email send failed: {e}")
        return False
